version: '3.3'

services:
  web:
    image: odoo:18.0
    depends_on:
      - db
    ports:
      - "8080:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    
    user: "0"
    volumes:
      - odoo-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
    networks:
      - odoo-test-net

  db:
    image: postgres:15
    restart: always
    ports:
      - "5209:5432"
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - odoo-test-net

networks:
  odoo-test-net:
    driver: bridge

volumes:
  odoo-data:
  postgres-data:
